# Generated by Django 4.1.4 on 2022-12-23 17:33

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('inertiatools', '0003_lease_property_rental_lease_rental_lease_tenant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rental',
            name='property',
        ),
        migrations.RemoveField(
            model_name='rental',
            name='tenants',
        ),
        migrations.RenameField(
            model_name='property',
            old_name='city',
            new_name='property_city',
        ),
        migrations.RenameField(
            model_name='property',
            old_name='address',
            new_name='property_street_name',
        ),
        migrations.RemoveField(
            model_name='property',
            name='state',
        ),
        migrations.RemoveField(
            model_name='property',
            name='zip_code',
        ),
        migrations.AddField(
            model_name='property',
            name='owner',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, to='inertiatools.owner'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='property',
            name='property_number',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='property',
            name='property_state',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='property',
            name='property_zip',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='property',
            name='unit_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.DeleteModel(
            name='Lease',
        ),
        migrations.DeleteModel(
            name='Rental',
        ),
    ]
